FROM mcr.microsoft.com/playwright:v1.46.1-jammy as playwright

WORKDIR /app

COPY package*.json .

RUN npm ci && npx playwright install --with-deps

COPY . .

RUN npm run build

CMD ["npx", "playwright", "test"]