name: ci-delivery-client

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'refactoring/**'
      - main
      - 'release/**'

jobs:
  lint_and_format:
    name: "Lint and Format Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:fix
      - name: Run eslint
        run: npm run lint:fix

  build_production:
    name: "Build Production Version"
    runs-on: ubuntu-latest
    needs: lint_and_format
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm ci
      - name: build production project
        run: npm run build

  playwright_tests:
    name: 'Run Playwright Tests'
    runs-on: ubuntu-latest
    needs: build_production
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Playwright Docker image
        run: docker build -f Dockerfile.tests -t wanderways-playwright .
      - name: Run Playwright tests
        run: docker run --rm wanderways-playwright npx playwright test

  docker_build:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    needs: playwright_tests
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest

